### ISSUE TITLE
Alternative to Numpy

### ISSUE THREAD

**Issue by abencomo** [mpatacchiola/dissecting-reinforcement-learning#1]
I would like to try your code on the [pyboard](http://micropython.org/) and the [OpenMV](https://openmv.io/products/openmv-cam) boards.  Unfortunately, Numpy is huge so it cannot be installed on a microcontroller.  Will it be possible to using list, a bytearray, or an array.array; to implement the functions you are using from numpy?

**Comment by mpatacchiola** [comment]
Hi abencomo

Yes sure, you can easily replace Numpy. In the code I provided I used Numpy only for element-wise matrix addiction and matrix-scalar multiplication. If you create your own function for these two operation you are done. I used matrices but you can use lists instead. However you should be careful because some algorithm are computationally expensive. The limited hardware of a microcontroller could take hours to converge to stable solutions. What I suggest you is to find an optimal policy running the script on a workstation and then load the policy in you microcontroller.
